services:
  redis:
    container_name: alice-med-redis
    image: "redis:alpine"
    command: redis-server --requirepass 1234560
    ports:
        - "6379:6379"
    volumes:
        - $PWD/local/redis-data:/var/lib/redis
        - $PWD/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_REPLICATION_MODE=master
volumes:
  db-data:
    driver: local
